booking:
  property: Booking Profile Prod
spring:
  data:
    mongodb:
      uri: mongodb+srv://scalde44:Scalderon4@clusterprueba.bzwwx.mongodb.net/?retryWrites=true&w=majority
      database: bookingdb
